dict/urls.py
from django.urls import path
from . import views

app_name = "dict"

urlpatterns = [
    path("", views.lookup, name='lookup')
]

lookup/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dict.urls')),
]

dict/models.py
from django.db import models

# Create your models here.

dict/forms.py
import requests
from django import forms


def find_key(json_input, key):
    if isinstance(json_input, dict):
        for k, v in json_input.items():
            if k == key:
                yield v
            if isinstance(v, (dict, list)):
                yield from find_key(v, key)
    elif isinstance(json_input, list):
        for item in json_input:
            yield from find_key(item, key)


class WordForm(forms.Form):
    word = forms.CharField(label='Your word', max_length=50)

    def search(self):
        result = {}
        searched_word = self.cleaned_data['word']
        if searched_word.isalpha():
            api_key = '57f42480-9178-4af8-9398-2f75f536fc08'
            api_url = f'''https://www.dictionaryapi.com/api/v3/references/learners/json/{searched_word}?key={api_key}'''
            response = requests.get(api_url)
            if response.status_code == 200:
                response = response.json()
                if response:
                    response_str = str(response)
                    if 'meta' in response_str:
                        response_object = response[0]
                        meta = response_object['meta']
                        stems = meta['stems']
                        exact_word = stems[0]
                        result['exact_word'] = exact_word.capitalize()
                        types = find_key(response_object, 'fl')
                        word_type = ''
                        for i in types:
                            word_type = i
                            break
                        result['type'] = word_type
                        ipa = response_object['hwi']['prs'][0]['ipa']
                        result['ipa'] = f'/{ipa}/'
                        audio = response_object['hwi']['prs'][0]['sound']['audio']
                        if not audio is None:
                            result['has_audio'] = True
                        subdirectory = audio[0]
                        prefixes = ['bix', 'gg', *tuple(list('0123456789'))]
                        for prefix in prefixes:
                            if audio.startswith(prefix, 0):
                                subdirectory = prefix
                        formats = ['mp3', 'wav', 'ogg']
                        audio_srcs = []
                        for ext in formats:
                            audio_srcs.append({
                                'src': f'''https://media.merriam-webster.com/audio/prons/en/us/mp3/{subdirectory}/{audio}.{ext}''',
                                'type': ext})
                        result['audio_srcs'] = audio_srcs

                        result['phrases'] = []
                        for phrase in stems[1:]:
                            result['phrases'].append(phrase.capitalize())
                        result['meanings'] = []
                        for meaning in response_object['shortdef']:
                            if not meaning[0].isalpha():
                                meaning = meaning[1:]
                            result['meanings'].append(meaning.capitalize())
                    else:
                        result['phrases'] = response
                else:
                    result['message'] = f'No results for "{searched_word}"'
            elif response.status_code == 500:
                result['message'] = 'Word not found'
            else:
                result['message'] = 'API not working'
        else:
            result['message'] = 'Invalid typing'
        return result

dict/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from .forms import WordForm


# Create your views here.
@csrf_exempt
def lookup(request):
    search_result = {}
    if request.method == "POST":
        form = WordForm(request.POST)
        if form.is_valid():
            search_result = form.search()
            search_result['success'] = True
    else:
        form = WordForm()
        search_result['success'] = False
    return render(request, 'dict/index.html', {'form': form, 'search_result': search_result, })

dict/templates/dict/index.html
{% extends 'admin/base.html' %}

{% block content %}
  <form id="word-form" class="d-flex gap-3" method="post">
    {% csrf_token %}
    <fieldset>
      <label for="look_up">Your word:</label>
      <input type="text" name="word" id="look_up" placeholder="Type here" />
    </fieldset>
    <input type="submit" value="Look up" />
  </form>
  <div id="result-of-form" class="">
    {% if search_result.success %}
      {% if search_result.message %}
        <strong class="text-capitalize">{{ search_result.message }}</strong>
      {% else %}
        <strong>Showing results for '{{ form.data.word }}'</strong>
        <p>
          <span class="fs-4 fw-bold text-primary">{{ search_result.exact_word }}</span> <span class="fst-italic text-info">{{ search_result.type }}</span> <span>{{ search_result.ipa }}</span>
        </p>

        {% if search_result.has_audio %}
          <audio controls>
            {% for audio_src in search_result.audio_srcs %}
              <source src="{{ audio_src.src }}" type="audio/{{ audio_src.type }}" />
            {% endfor %}Your browser does not support the audio element.
          </audio>
        {% endif %}

        {% if search_result.meanings %}
          <h5 class="text-warning">Definitions:</h5>
          <ul class="text-secondary">
            {% for meaning in search_result.meanings %}
              <li>{{ meaning }}</li>
            {% endfor %}
          </ul>
        {% endif %}
        <h5 class="text-warning">Frequently used in phrases:</h5>
        <ul>
          {% for phrase in search_result.phrases %}
            <li class="text-body-secondary">{{ phrase }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    {% else %}
      <h1 id="welcome" class="text-body-tertiary">Welcome to My LookUp</h1>
    {% endif %}
  </div>
{% endblock %}

{% block script %}
  <script>
    $(document).ready(function () {
      $('#word-form').submit(function (e) {
        e.preventDefault();
        $.ajax({
          type: 'POST',
          url: "{% url 'dict:lookup' %}",
          data: {
            $(this).serialize(),
          },
          success: function (response) {
            $('#word-form').trigger('reset')
            $('#result-of-form').removeClass('d-none')
            $('#welcome').toggleClass('d-none')
          },
        })
      })
    })
  </script>
{% endblock %}